apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}-route
  labels:
    app: {{ .Values.appName }}
    environment: dev
spec:
  to:
    kind: Service
    name: {{ .Values.appName }}
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
